version: '3.9'

services:
  bot:
    build: .
    image: moodle-outlook-sync-bot
    volumes:
      - "./config.yaml:/app/config.yaml"
      - "./docker-scripts/crontab.txt:/scripts/crontab.txt"
    stop_grace_period: 3s